### ISSUE TITLE
property:givenName

### ISSUE THREAD

**Issue by dshorthouse** [tdwg/attribution#18]
### givenName (property)
|  |  |
| ---- | ---- |
| **Definition** | Given name. In the U.S., the first name of a Person. This can be used along with familyName instead of the name property. |
| **Existing property** | givenName |
| **Existing namespace** | https://schema.org/ |
| **Existing property identifier** | https://schema.org/givenName |
| **Format** | string |
| **Required** | no |
| **Constraints** | |
| **Examples** | "Margaret" |
| **Notes** | |

**Comment by PietrH** [comment]
What about additional names as an external subproperty: https://schema.org/additionalName ?

As in Charles **Robert** Darwin

**Comment by dshorthouse** [comment]
@PietrH Yes, that's a logical one and easy to add. I believe I included it in earlier renditions but began questioning the potential for insensitivity to cultural preferences & so opted for a more generic #21. However, that property as defined is more tuned to what's transcribed directly from the label on the specimen.

**Comment by PietrH** [comment]
@dshorthouse Something like a middle name might prove of value in disambiguation, but might not neccesairly be included in the verbatimName #21 for every record. I have certainly used them for reconciliation. 

But it does add complexity and indeed the potential for insensitivity. I believe wikidata handles this as a nominal order of given names. Though the order might sometimes be unknown.

**Comment by dshorthouse** [comment]
@PietrH I'll add it. #33

**Comment by dshorthouse** [comment]
Agreed 2020-06-24 with working group that this term is culturally insensitive and should not be part of the extension.
