### ISSUE TITLE
property:additionalName

### ISSUE THREAD

**Issue by dshorthouse** [tdwg/attribution#33]
### additionalName (property)
|  |  |
| ---- | ---- |
| **Definition** |  An additional name for a Person, can be used for a middle name.  |
| **Existing property** | additionalName |
| **Existing namespace** | https://schema.org/  |
| **Existing property identifier** | https://schema.org/additionalName |
| **Format** | string |
| **Required** | no  |
| **Constraints** |  |
| **Examples** | Robert |
| **Notes** |  |

**Comment by matdillen** [comment]
This definition is inherited from schema.org, but I still wonder: This field cannot be used for a non-Person agent? Do we have an example/use case of how this field is to be used? Can it be used for first names or nicknames?

**Comment by dshorthouse** [comment]
Because we've settled on using [name](https://github.com/tdwg/attribution/issues/17 ) & deprecated other schema.org-based terms that contains parts of names, I wonder if we should deprecate this term altogether. Any objections?

**Comment by matdillen** [comment]
That was my first thought as well when going over the current set of terms. But this may be awkward if the term has already been put to use?

**Comment by dshorthouse** [comment]
@matdillen If the other terms, `name` and `alternateName` have been used, I don't expect deprecating this one now will be a problem, especially since we have not yet gone to production.

**Comment by matdillen** [comment]
Then I would suggest deprecating this one.
